#!/bin/sh
# File generated by ocamlbuild

cd /home/eduardo/Documentos/Faculdade/Compiladores/AnalisadorSintaticoMenhir/portugol

rm -f ast.cmi
rm -f ast.cmo
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
rm -f parser.mli
# Also clean the script itself
rm -f /home/eduardo/Documentos/Faculdade/Compiladores/AnalisadorSintaticoMenhir/portugol/_build/sanitize.sh
